trigger: none

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build  
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'acr'
        repository: 'acrrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
